name: Hello world
on: [workflow_dispatch, pull_request]
jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo Hello world!
      - name: Ls /
        run: ls /
